# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ced < Formula
  desc "ced — opinionated mouse-first terminal code editor."
  homepage "https://github.com/rohanthewiz/ced"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rohanthewiz/ced/releases/download/v0.2.0/ced_0.2.0_darwin_amd64.tar.gz"
      sha256 "6985e6c7df20875530f481beac64c0db82ca140f24c639144baa2fc81bf6895b"

      define_method(:install) do
        bin.install "ced"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rohanthewiz/ced/releases/download/v0.2.0/ced_0.2.0_darwin_arm64.tar.gz"
      sha256 "ee29c21a01a8314b74c0d09c9cd9f5427e744be17831796f1e12eec8ec8c9cac"

      define_method(:install) do
        bin.install "ced"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rohanthewiz/ced/releases/download/v0.2.0/ced_0.2.0_linux_amd64.tar.gz"
      sha256 "6956f2918c279c32b3170e5d433af5d44f086e408de64d65f0ec86f4da6683df"
      define_method(:install) do
        bin.install "ced"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rohanthewiz/ced/releases/download/v0.2.0/ced_0.2.0_linux_arm64.tar.gz"
      sha256 "5a18bc7802fcee661afe4d4e29163bf76cce0d19e75c01724bb4127ac4cfdc82"
      define_method(:install) do
        bin.install "ced"
      end
    end
  end

  test do
    assert_path_exists bin/"ced"
  end
end
