// =============================================================================
// File: internal/editor/multiedit.go
// Author: Rohan Allison <rohanthewiz@gmail.com>
// Created: 2026-08-03
// Copyright: 2026 Rohan Allison. All rights reserved.
// =============================================================================

// multiedit.go applies a SET of ranged replacements to one buffer as a
// single undoable step. It is the buffer-layer half of the workspace-edit
// primitive: the cross-file orchestration lives in app/workspaceedit.go,
// and everything about URIs, UTF-16 columns and which files are open stops
// at that boundary. What arrives here is already rune coordinates against
// this buffer.
//
// The shape is lifted wholesale from ReplaceAll (replace.go), which had
// been the codebase's only multi-range edit and stated the two rules this
// file now owns:
//
// ONE SNAPSHOT UP FRONT, then edit the Buffer directly. The Buffer
// primitives record no history, so a hundred replacements cost exactly one
// undo step WITHOUT going near undoSuppress — that flag belongs to the
// multi-caret fan-out alone, and an unbalanced `true` silently disables
// undo for the rest of the session.
//
// BOTTOM-UP, ALWAYS. An edit can only move text that comes AFTER it, so
// applying from the end of the document means every position still waiting
// is still correct. Top-down invalidates every edit below the first one —
// and by a different amount per line when the replacement isn't the same
// width as what it replaced, which is the flavour of bug that survives a
// test suite because it only appears on the second edit of a line.
//
// The one thing ReplaceAll never had to think about is that a caller's
// edits come from OUTSIDE. A find-and-replace set is generated by one
// scanner and is well-formed by construction; a language server's is not
// necessarily, so OverlapIndex exists to turn a server that breaks the
// spec's no-overlap rule into a refusal rather than a corrupted file.

package editor

import "sort"

// Edit is one replacement in buffer coordinates: everything in
// [Start, End) becomes NewText. A zero-width range (Start == End) is a
// pure insertion, which is what a server sends for "add an import here".
type Edit struct {
	Start   Position
	End     Position
	NewText string
}

// EditResult is where one edit's new text ended up once the whole set has
// been applied — the range it occupies in the FINAL buffer, which is not
// where it started if an earlier edit on the same line changed width.
type EditResult struct {
	Start Position
	End   Position
}

// SortEdits sorts a set into ascending document order, in place.
//
// The sort is STABLE, and that is load-bearing rather than incidental:
// two zero-width inserts at the same position are legal (the spec says
// the array order decides which text lands first), and only a stable sort
// preserves that order among equal positions. ApplyEdits then walks the
// sorted set BACKWARDS, so equal positions are inserted in reverse array
// order — which is exactly what makes a caller's [A, B] come out as "AB".
func SortEdits(edits []Edit) {
	sort.SliceStable(edits, func(i, j int) bool {
		if edits[i].Start != edits[j].Start {
			return PosLess(edits[i].Start, edits[j].Start)
		}
		return PosLess(edits[i].End, edits[j].End)
	})
}

// NormalizeEdits puts every edit's endpoints in document order and then
// sorts the set. A server is entitled to send a reversed range, and one
// slipping through would make OverlapIndex's comparison meaningless.
func NormalizeEdits(edits []Edit) {
	for i := range edits {
		edits[i].Start, edits[i].End = PosOrdered(edits[i].Start, edits[i].End)
	}
	SortEdits(edits)
}

// OverlapIndex returns the index of the first edit in a SORTED set that
// overlaps the one before it, or -1 when the set is clean.
//
// Touching is fine and overlapping is not: an end equal to the next start
// means two adjacent replacements, which is a perfectly ordinary way to
// rewrite `a.b` into `c.d`. An end PAST the next start means the two
// disagree about what the text there is, and the LSP spec forbids it
// within a single document for that reason.
//
// Refusing rather than applying anyway is the whole point. Overlapping
// edits applied bottom-up don't fail — they produce plausible-looking
// garbage, which is the one outcome worse than an error message.
func OverlapIndex(sorted []Edit) int {
	for i := 1; i < len(sorted); i++ {
		if PosLess(sorted[i].Start, sorted[i-1].End) {
			return i
		}
	}
	return -1
}

// ApplyEdits applies a sorted, non-overlapping set to b and reports how
// many landed. It records NO undo history — that is the caller's single
// snapshot to file, and is what keeps a whole workspace edit to one step.
//
// Endpoints are resolved through ClampEnd rather than Clamp so a range
// ending past the last line means "through the end of the buffer", which
// is how a server spells a whole-document rewrite.
func ApplyEdits(b *Buffer, sorted []Edit) int {
	if b == nil {
		return 0
	}
	n := 0
	// Descending: see the file comment. Every edit still waiting sits
	// ABOVE the one being applied, so nothing that has been visited can
	// move it.
	for i := len(sorted) - 1; i >= 0; i-- {
		start := b.Clamp(sorted[i].Start)
		end := b.ClampEnd(sorted[i].End)
		b.DeleteRange(start, end)
		b.InsertString(start, sorted[i].NewText)
		n++
	}
	return n
}

// EditResults reports where each edit in a sorted set ends up after the
// whole set has been applied. Pure — it reads no buffer, deriving the
// shift from the edits alone.
//
// It is computed rather than recorded because the apply runs bottom-up:
// a position recorded as an edit landed would be correct at that instant
// and wrong by the time the pass finished, since every LATER edit in the
// array is applied BEFORE it. Walking ascending here, where each edit's
// displacement is the sum of what its predecessors did, avoids the whole
// fixup problem.
//
// Two accumulators, and the second is the subtle one:
//
//   - lineShift is how many lines the edits so far added or removed, and
//     applies to every position after them.
//   - colShift only applies while we are still on the SAME final line as
//     the previous edit's end. Once an edit lands on a new original line,
//     the columns of that line are untouched by anything before it.
func EditResults(sorted []Edit) []EditResult {
	out := make([]EditResult, len(sorted))
	lineShift, colShift := 0, 0
	prevEndLine := -1
	for i, e := range sorted {
		startLine := e.Start.Line + lineShift
		startCol := e.Start.Col
		// The column shift only survives while we are still on the line the
		// previous edit ENDED on. A new original line's columns are
		// untouched by anything that came before it.
		if e.Start.Line == prevEndLine {
			startCol += colShift
		}

		// Where the replacement text itself ends, measured from the start
		// it was just placed at.
		addLines, lastLen := textShape(e.NewText)
		endLine, endCol := startLine+addLines, lastLen
		if addLines == 0 {
			endCol = startCol + lastLen
		}

		// The edit consumed (End.Line - Start.Line) lines and produced
		// addLines, so everything below moves by the difference.
		lineShift += addLines - (e.End.Line - e.Start.Line)
		// The tail of the original end line now sits at endCol instead of
		// End.Col, so a later edit on that same original line shifts by
		// the difference.
		colShift = endCol - e.End.Col
		prevEndLine = e.End.Line

		out[i] = EditResult{
			Start: Position{Line: startLine, Col: startCol},
			End:   Position{Line: endLine, Col: endCol},
		}
	}
	return out
}

// textShape reports how many newlines text carries and the rune length of
// its final line — the two numbers that say where a piece of inserted text
// ends relative to where it started.
func textShape(text string) (newlines, lastLineLen int) {
	last := 0
	for i, r := range text {
		if r == '\n' {
			newlines++
			last = i + 1
		}
	}
	return newlines, len([]rune(text[last:]))
}

// ApplyMultiEdit applies a set of edits to the tab as ONE undo step and
// reports how many landed, along with where each one ended up.
//
// The set is normalised and checked here rather than trusted, because the
// callers that need this primitive (a language server's workspace edit, a
// refactoring) are precisely the ones whose edits ced did not generate.
// An overlapping set is refused whole: ok is false, the buffer is
// untouched, and no snapshot is filed.
//
// The tail is ReplaceAll's, verb for verb, and every line of it is load
// bearing — see replace.go for why each one is there.
func (t *Tab) ApplyMultiEdit(edits []Edit) (results []EditResult, ok bool) {
	if t == nil || t.Buffer == nil || t.IsImage() || len(edits) == 0 {
		return nil, false
	}
	set := make([]Edit, len(edits))
	copy(set, edits)
	NormalizeEdits(set)
	if OverlapIndex(set) >= 0 {
		return nil, false
	}

	t.pushUndo(undoGroupStructural)
	// Carets and any selection were measured against the buffer this is
	// about to rewrite; keeping either would leave the next keystroke
	// editing text that moved.
	t.Carets = nil
	results = EditResults(set)
	ApplyEdits(t.Buffer, set)

	t.Dirty = true
	t.EditRev++
	// Structural by definition — a replacement may carry newlines, and a
	// set of them has changed enough of the file that patching the style
	// grid row by row would cost more than the re-lex. This is the
	// InvalidateStyles default the syntax layer asks of any new mutator
	// that can't prove its rows still line up.
	t.InvalidateStyles()
	// The cursor may now point past the end of a shortened line.
	t.Cursor = t.Buffer.Clamp(t.Cursor)
	t.Anchor = t.Cursor
	t.cursorMoved = true
	return results, true
}
